// <auto-generated />
using System;
using Internshala.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Internshala.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260530062025_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Internshala.Domain.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AvailabilityDate")
                        .HasColumnType("date");

                    b.Property<string>("CoverLetter")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("EmployerNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ExpectedStipend")
                        .HasColumnType("int");

                    b.Property<int?>("InternshipId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("ListingType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ResumeUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("WithdrawnAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("InternshipId", "IsDeleted");

                    b.HasIndex("StudentId", "InternshipId")
                        .IsUnique()
                        .HasFilter("[InternshipId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("StudentId", "IsDeleted");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.ApplicationStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ApplicationStatusHistories");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3197),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Engineering & Technology",
                            Slug = "engineering-technology",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3206)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3215),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Marketing",
                            Slug = "marketing",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3216)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3217),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Business Development",
                            Slug = "business-development",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3218)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3219),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Finance & Accounting",
                            Slug = "finance-accounting",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3219)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3221),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Human Resources",
                            Slug = "human-resources",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3221)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3222),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Design & UX",
                            Slug = "design-ux",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3223)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3224),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Content & Journalism",
                            Slug = "content-journalism",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3224)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3226),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Data Science & Analytics",
                            Slug = "data-science-analytics",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3226)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3227),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Operations",
                            Slug = "operations",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3228)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3229),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sales",
                            Slug = "sales",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3229)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3230),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Legal",
                            Slug = "legal",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3231)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3232),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Education & Teaching",
                            Slug = "education-teaching",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3232)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3234),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Healthcare & Medicine",
                            Slug = "healthcare-medicine",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3234)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3235),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Social Media",
                            Slug = "social-media",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3236)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3239),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Research",
                            Slug = "research",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3250)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3251),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Architecture",
                            Slug = "architecture",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3252)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3253),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Event Management",
                            Slug = "event-management",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3253)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3255),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Supply Chain",
                            Slug = "supply-chain",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3255)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3256),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Media & Entertainment",
                            Slug = "media-entertainment",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3256)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3258),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "NGO / Social Work",
                            Slug = "ngo-social-work",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3258)
                        });
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<short?>("EndYear")
                        .HasColumnType("smallint");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("Grade")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<short>("StartYear")
                        .HasColumnType("smallint");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyLogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanySize")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CompanyWebsite")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<short?>("Founded")
                        .HasColumnType("smallint");

                    b.Property<string>("HeadquartersCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IndustryId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employers");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Internship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ApplicationDeadline")
                        .HasColumnType("date");

                    b.Property<int>("ApplicationsCount")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DurationMonths")
                        .HasColumnType("tinyint");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FeaturedUntil")
                        .HasColumnType("date");

                    b.Property<string>("InternshipType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<short>("OpeningsCount")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsibilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StartDateType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StipendMax")
                        .HasColumnType("int");

                    b.Property<int?>("StipendMin")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EmployerId");

                    b.HasIndex("LocationId");

                    b.HasIndex("IsDeleted", "IsActive", "Status", "CategoryId", "LocationId");

                    b.ToTable("Internships");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ApplicationDeadline")
                        .HasColumnType("date");

                    b.Property<int>("ApplicationsCount")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<int?>("ExperienceYearsMin")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("SalaryMax")
                        .HasColumnType("int");

                    b.Property<int?>("SalaryMin")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EmployerId");

                    b.HasIndex("LocationId");

                    b.HasIndex("IsDeleted", "IsActive", "Status", "CategoryId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityName");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityName = "Bangalore",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3909),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Karnataka",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3909)
                        },
                        new
                        {
                            Id = 2,
                            CityName = "Mumbai",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3914),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Maharashtra",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3914)
                        },
                        new
                        {
                            Id = 3,
                            CityName = "Delhi",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3916),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Delhi",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3916)
                        },
                        new
                        {
                            Id = 4,
                            CityName = "Hyderabad",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3918),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Telangana",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3918)
                        },
                        new
                        {
                            Id = 5,
                            CityName = "Chennai",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3919),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Tamil Nadu",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3920)
                        },
                        new
                        {
                            Id = 6,
                            CityName = "Pune",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3921),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Maharashtra",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3921)
                        },
                        new
                        {
                            Id = 7,
                            CityName = "Kolkata",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3923),
                            IsActive = true,
                            IsDeleted = false,
                            State = "West Bengal",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3923)
                        },
                        new
                        {
                            Id = 8,
                            CityName = "Ahmedabad",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3926),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Gujarat",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3927)
                        },
                        new
                        {
                            Id = 9,
                            CityName = "Jaipur",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3928),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Rajasthan",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3928)
                        },
                        new
                        {
                            Id = 10,
                            CityName = "Lucknow",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3929),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Uttar Pradesh",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3930)
                        },
                        new
                        {
                            Id = 11,
                            CityName = "Noida",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3931),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Uttar Pradesh",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3931)
                        },
                        new
                        {
                            Id = 12,
                            CityName = "Gurgaon",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3933),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Haryana",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3933)
                        },
                        new
                        {
                            Id = 13,
                            CityName = "Kochi",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3934),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Kerala",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3935)
                        },
                        new
                        {
                            Id = 14,
                            CityName = "Bhubaneswar",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3936),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Odisha",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3936)
                        },
                        new
                        {
                            Id = 15,
                            CityName = "Coimbatore",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3937),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Tamil Nadu",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3938)
                        },
                        new
                        {
                            Id = 16,
                            CityName = "Indore",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3939),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Madhya Pradesh",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3939)
                        },
                        new
                        {
                            Id = 17,
                            CityName = "Chandigarh",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3941),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Punjab",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3941)
                        },
                        new
                        {
                            Id = 18,
                            CityName = "Nagpur",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3942),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Maharashtra",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3942)
                        },
                        new
                        {
                            Id = 19,
                            CityName = "Visakhapatnam",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3944),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Andhra Pradesh",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3944)
                        },
                        new
                        {
                            Id = 20,
                            CityName = "Surat",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3945),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Gujarat",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(3945)
                        },
                        new
                        {
                            Id = 21,
                            CityName = "Mysore",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4009),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Karnataka",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4010)
                        },
                        new
                        {
                            Id = 22,
                            CityName = "Thiruvananthapuram",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4011),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Kerala",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4012)
                        },
                        new
                        {
                            Id = 23,
                            CityName = "Patna",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4013),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Bihar",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4014)
                        },
                        new
                        {
                            Id = 24,
                            CityName = "Bhopal",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4015),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Madhya Pradesh",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4015)
                        },
                        new
                        {
                            Id = 25,
                            CityName = "Vadodara",
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4017),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Gujarat",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4017)
                        });
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId", "RevokedAt");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Resume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4149),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Python",
                            Slug = "python",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4149)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4154),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "JavaScript",
                            Slug = "javascript",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4154)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4156),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "React",
                            Slug = "react",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4157)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4158),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Angular",
                            Slug = "angular",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4159)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4160),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Node.js",
                            Slug = "nodejs",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4161)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4162),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Java",
                            Slug = "java",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4163)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4164),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "C#",
                            Slug = "csharp",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4165)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4166),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "SQL",
                            Slug = "sql",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4167)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4168),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Machine Learning",
                            Slug = "machine-learning",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4169)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4170),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Data Analysis",
                            Slug = "data-analysis",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4171)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4172),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Digital Marketing",
                            Slug = "digital-marketing",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4173)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4174),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "SEO",
                            Slug = "seo",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4175)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4176),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Content Writing",
                            Slug = "content-writing",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4177)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4178),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Graphic Design",
                            Slug = "graphic-design",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4179)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4180),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Figma",
                            Slug = "figma",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4181)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4182),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Excel",
                            Slug = "excel",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4183)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4185),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Communication",
                            Slug = "communication",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4185)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4186),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Leadership",
                            Slug = "leadership",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4187)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4188),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Canva",
                            Slug = "canva",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4189)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4190),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "AWS",
                            Slug = "aws",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4191)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4192),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Docker",
                            Slug = "docker",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4193)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4194),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Git",
                            Slug = "git",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4195)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4196),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Flutter",
                            Slug = "flutter",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4197)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4198),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "React Native",
                            Slug = "react-native",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4198)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4200),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "PowerBI",
                            Slug = "powerbi",
                            UpdatedAt = new DateTime(2026, 5, 30, 6, 20, 22, 186, DateTimeKind.Utc).AddTicks(4200)
                        });
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CourseOfStudy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CurrentInstitution")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GitHubUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("Gpa")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<short?>("GraduationYear")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProfileComplete")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PortfolioUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte>("ProfileCompleteness")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InternshipSkills", b =>
                {
                    b.Property<int>("InternshipsId")
                        .HasColumnType("int");

                    b.Property<int>("SkillsId")
                        .HasColumnType("int");

                    b.HasKey("InternshipsId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("InternshipSkills");
                });

            modelBuilder.Entity("JobSkills", b =>
                {
                    b.Property<int>("JobsId")
                        .HasColumnType("int");

                    b.Property<int>("SkillsId")
                        .HasColumnType("int");

                    b.HasKey("JobsId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("JobSkills");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Application", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Internship", "Internship")
                        .WithMany("Applications")
                        .HasForeignKey("InternshipId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Internshala.Domain.Entities.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Internshala.Domain.Entities.Student", "Student")
                        .WithMany("Applications")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Internship");

                    b.Navigation("Job");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.ApplicationStatusHistory", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Application", "Application")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Education", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Student", "Student")
                        .WithMany("Educations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Employer", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Category", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Internshala.Domain.Entities.User", "User")
                        .WithOne("Employer")
                        .HasForeignKey("Internshala.Domain.Entities.Employer", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Industry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Experience", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Student", "Student")
                        .WithMany("Experiences")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Internship", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Internshala.Domain.Entities.Employer", "Employer")
                        .WithMany("Internships")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Internshala.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Employer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Job", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Internshala.Domain.Entities.Employer", "Employer")
                        .WithMany("Jobs")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Internshala.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Employer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Resume", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Student", "Student")
                        .WithOne("Resume")
                        .HasForeignKey("Internshala.Domain.Entities.Resume", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Student", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("Internshala.Domain.Entities.Student", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternshipSkills", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Internship", null)
                        .WithMany()
                        .HasForeignKey("InternshipsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Internshala.Domain.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobSkills", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Job", null)
                        .WithMany()
                        .HasForeignKey("JobsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Internshala.Domain.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Application", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Employer", b =>
                {
                    b.Navigation("Internships");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Internship", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Job", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Student", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.User", b =>
                {
                    b.Navigation("Employer");

                    b.Navigation("Notifications");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
