// <auto-generated />
using System;
using Internshala.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Internshala.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Internshala.Domain.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AvailabilityDate")
                        .HasColumnType("date");

                    b.Property<string>("CoverLetter")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("EmployerNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ExpectedStipend")
                        .HasColumnType("int");

                    b.Property<int?>("InternshipId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("ListingType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ResumeUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("WithdrawnAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("InternshipId", "IsDeleted");

                    b.HasIndex("StudentId", "InternshipId")
                        .IsUnique()
                        .HasFilter("[InternshipId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("StudentId", "IsDeleted");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.ApplicationStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ApplicationStatusHistories");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6446),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Engineering & Technology",
                            Slug = "engineering-technology",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6447)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6450),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Marketing",
                            Slug = "marketing",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6450)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6451),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Business Development",
                            Slug = "business-development",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6452)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6452),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Finance & Accounting",
                            Slug = "finance-accounting",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6453)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6453),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Human Resources",
                            Slug = "human-resources",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6453)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6454),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Design & UX",
                            Slug = "design-ux",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6454)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6455),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Content & Journalism",
                            Slug = "content-journalism",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6455)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6456),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Data Science & Analytics",
                            Slug = "data-science-analytics",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6456)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6457),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Operations",
                            Slug = "operations",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6457)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6457),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sales",
                            Slug = "sales",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6458)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6458),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Legal",
                            Slug = "legal",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6458)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6459),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Education & Teaching",
                            Slug = "education-teaching",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6459)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6460),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Healthcare & Medicine",
                            Slug = "healthcare-medicine",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6460)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6460),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Social Media",
                            Slug = "social-media",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6461)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6461),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Research",
                            Slug = "research",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6461)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6462),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Architecture",
                            Slug = "architecture",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6462)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6463),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Event Management",
                            Slug = "event-management",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6463)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6464),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Supply Chain",
                            Slug = "supply-chain",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6464)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6464),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Media & Entertainment",
                            Slug = "media-entertainment",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6464)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6465),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "NGO / Social Work",
                            Slug = "ngo-social-work",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6465)
                        });
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<int>("EnrolledCount")
                        .HasColumnType("int");

                    b.Property<string>("Instructor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Prerequisites")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("WhatYouLearn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsDeleted", "IsPublished", "CategoryId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.CourseModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPreview")
                        .HasColumnType("bit");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("CourseModules");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<short?>("EndYear")
                        .HasColumnType("smallint");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("Grade")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<short>("StartYear")
                        .HasColumnType("smallint");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyLogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanySize")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CompanyWebsite")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<short?>("Founded")
                        .HasColumnType("smallint");

                    b.Property<string>("HeadquartersCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IndustryId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employers");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompletedModules")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("ProgressPercent")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Internship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ApplicationDeadline")
                        .HasColumnType("date");

                    b.Property<int>("ApplicationsCount")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DurationMonths")
                        .HasColumnType("tinyint");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FeaturedUntil")
                        .HasColumnType("date");

                    b.Property<string>("InternshipType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<short>("OpeningsCount")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsibilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StartDateType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StipendMax")
                        .HasColumnType("int");

                    b.Property<int?>("StipendMin")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EmployerId");

                    b.HasIndex("LocationId");

                    b.HasIndex("IsDeleted", "IsActive", "Status", "CategoryId", "LocationId");

                    b.ToTable("Internships");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ApplicationDeadline")
                        .HasColumnType("date");

                    b.Property<int>("ApplicationsCount")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<int?>("ExperienceYearsMin")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("SalaryMax")
                        .HasColumnType("int");

                    b.Property<int?>("SalaryMin")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EmployerId");

                    b.HasIndex("LocationId");

                    b.HasIndex("IsDeleted", "IsActive", "Status", "CategoryId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityName");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityName = "Bangalore",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6563),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Karnataka",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6563)
                        },
                        new
                        {
                            Id = 2,
                            CityName = "Mumbai",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6564),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Maharashtra",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6565)
                        },
                        new
                        {
                            Id = 3,
                            CityName = "Delhi",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6565),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Delhi",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6566)
                        },
                        new
                        {
                            Id = 4,
                            CityName = "Hyderabad",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6566),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Telangana",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6566)
                        },
                        new
                        {
                            Id = 5,
                            CityName = "Chennai",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6567),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Tamil Nadu",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6567)
                        },
                        new
                        {
                            Id = 6,
                            CityName = "Pune",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6568),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Maharashtra",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6568)
                        },
                        new
                        {
                            Id = 7,
                            CityName = "Kolkata",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6569),
                            IsActive = true,
                            IsDeleted = false,
                            State = "West Bengal",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6569)
                        },
                        new
                        {
                            Id = 8,
                            CityName = "Ahmedabad",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6569),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Gujarat",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6570)
                        },
                        new
                        {
                            Id = 9,
                            CityName = "Jaipur",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6570),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Rajasthan",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6570)
                        },
                        new
                        {
                            Id = 10,
                            CityName = "Lucknow",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6571),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Uttar Pradesh",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6571)
                        },
                        new
                        {
                            Id = 11,
                            CityName = "Noida",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6572),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Uttar Pradesh",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6572)
                        },
                        new
                        {
                            Id = 12,
                            CityName = "Gurgaon",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6573),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Haryana",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6573)
                        },
                        new
                        {
                            Id = 13,
                            CityName = "Kochi",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6573),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Kerala",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6573)
                        },
                        new
                        {
                            Id = 14,
                            CityName = "Bhubaneswar",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6574),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Odisha",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6574)
                        },
                        new
                        {
                            Id = 15,
                            CityName = "Coimbatore",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6575),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Tamil Nadu",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6575)
                        },
                        new
                        {
                            Id = 16,
                            CityName = "Indore",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6576),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Madhya Pradesh",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6576)
                        },
                        new
                        {
                            Id = 17,
                            CityName = "Chandigarh",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6576),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Punjab",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6577)
                        },
                        new
                        {
                            Id = 18,
                            CityName = "Nagpur",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6577),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Maharashtra",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6577)
                        },
                        new
                        {
                            Id = 19,
                            CityName = "Visakhapatnam",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6578),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Andhra Pradesh",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6578)
                        },
                        new
                        {
                            Id = 20,
                            CityName = "Surat",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6579),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Gujarat",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6579)
                        },
                        new
                        {
                            Id = 21,
                            CityName = "Mysore",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6603),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Karnataka",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6603)
                        },
                        new
                        {
                            Id = 22,
                            CityName = "Thiruvananthapuram",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6604),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Kerala",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6604)
                        },
                        new
                        {
                            Id = 23,
                            CityName = "Patna",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6604),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Bihar",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6604)
                        },
                        new
                        {
                            Id = 24,
                            CityName = "Bhopal",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6605),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Madhya Pradesh",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6605)
                        },
                        new
                        {
                            Id = 25,
                            CityName = "Vadodara",
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6606),
                            IsActive = true,
                            IsDeleted = false,
                            State = "Gujarat",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6606)
                        });
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId", "RevokedAt");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Resume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6634),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Python",
                            Slug = "python",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6634)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6637),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "JavaScript",
                            Slug = "javascript",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6637)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6638),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "React",
                            Slug = "react",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6638)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6639),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Angular",
                            Slug = "angular",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6639)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6640),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Node.js",
                            Slug = "nodejs",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6640)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6641),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Java",
                            Slug = "java",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6641)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6642),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "C#",
                            Slug = "csharp",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6642)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6643),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "SQL",
                            Slug = "sql",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6643)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6644),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Machine Learning",
                            Slug = "machine-learning",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6644)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6645),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Data Analysis",
                            Slug = "data-analysis",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6645)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6645),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Digital Marketing",
                            Slug = "digital-marketing",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6646)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6646),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "SEO",
                            Slug = "seo",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6647)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6647),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Content Writing",
                            Slug = "content-writing",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6648)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6648),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Graphic Design",
                            Slug = "graphic-design",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6648)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6649),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Figma",
                            Slug = "figma",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6649)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6650),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Excel",
                            Slug = "excel",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6650)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6651),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Communication",
                            Slug = "communication",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6651)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6652),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Leadership",
                            Slug = "leadership",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6652)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6653),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Canva",
                            Slug = "canva",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6653)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6654),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "AWS",
                            Slug = "aws",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6654)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6655),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Docker",
                            Slug = "docker",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6655)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6656),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Git",
                            Slug = "git",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6656)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6657),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Flutter",
                            Slug = "flutter",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6657)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6658),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "React Native",
                            Slug = "react-native",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6658)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6658),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "PowerBI",
                            Slug = "powerbi",
                            UpdatedAt = new DateTime(2026, 6, 3, 10, 58, 33, 209, DateTimeKind.Utc).AddTicks(6659)
                        });
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CourseOfStudy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CurrentInstitution")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GitHubUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("Gpa")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<short?>("GraduationYear")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProfileComplete")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PortfolioUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte>("ProfileCompleteness")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InternshipSkills", b =>
                {
                    b.Property<int>("InternshipsId")
                        .HasColumnType("int");

                    b.Property<int>("SkillsId")
                        .HasColumnType("int");

                    b.HasKey("InternshipsId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("InternshipSkills");
                });

            modelBuilder.Entity("JobSkills", b =>
                {
                    b.Property<int>("JobsId")
                        .HasColumnType("int");

                    b.Property<int>("SkillsId")
                        .HasColumnType("int");

                    b.HasKey("JobsId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("JobSkills");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Application", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Internship", "Internship")
                        .WithMany("Applications")
                        .HasForeignKey("InternshipId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Internshala.Domain.Entities.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Internshala.Domain.Entities.Student", "Student")
                        .WithMany("Applications")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Internship");

                    b.Navigation("Job");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.ApplicationStatusHistory", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Application", "Application")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Course", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.CourseModule", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Education", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Student", "Student")
                        .WithMany("Educations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Employer", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Category", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Internshala.Domain.Entities.User", "User")
                        .WithOne("Employer")
                        .HasForeignKey("Internshala.Domain.Entities.Employer", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Industry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Internshala.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Experience", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Student", "Student")
                        .WithMany("Experiences")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Internship", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Internshala.Domain.Entities.Employer", "Employer")
                        .WithMany("Internships")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Internshala.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Employer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Job", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Internshala.Domain.Entities.Employer", "Employer")
                        .WithMany("Jobs")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Internshala.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Employer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Resume", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Student", "Student")
                        .WithOne("Resume")
                        .HasForeignKey("Internshala.Domain.Entities.Resume", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Student", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("Internshala.Domain.Entities.Student", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternshipSkills", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Internship", null)
                        .WithMany()
                        .HasForeignKey("InternshipsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Internshala.Domain.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobSkills", b =>
                {
                    b.HasOne("Internshala.Domain.Entities.Job", null)
                        .WithMany()
                        .HasForeignKey("JobsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Internshala.Domain.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Application", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Employer", b =>
                {
                    b.Navigation("Internships");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Internship", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Job", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.Student", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("Internshala.Domain.Entities.User", b =>
                {
                    b.Navigation("Employer");

                    b.Navigation("Notifications");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
